#Scribd Account Info


key: 2dgy1dc2g2ni7ckwot3zo
secret: sec-8ajrryzrl8i8utxycosh66kw98
user: dissers
password:
access: private
#storage: s3 # Uncomment if Attachment_fu is using Amazon S3 for storage

